import {
  Invoice,
  HostRoom as Room,
  Tenant,
  UtilityBill,
  UtilityType,
  UtilityTypeMeta,
} from '@hostelhive/data-access';

/** Stub rooms (Q-API pending). Matches design-mockups/12-rooms.html. */
export const ROOMS: Room[] = [
  {
    id: 'r101',
    number: '101',
    floor: 'Ground',
    type: '2-sharing',
    capacity: 2,
    occupied: 2,
    rentPerBed: 14000,
    attachedBath: true,
    createdAt: '',
  },
  {
    id: 'r102',
    number: '102',
    floor: 'Ground',
    type: '3-sharing',
    capacity: 3,
    occupied: 2,
    rentPerBed: 12000,
    attachedBath: false,
    createdAt: '',
  },
  {
    id: 'r201',
    number: '201',
    floor: '1st',
    type: '1-sharing',
    capacity: 1,
    occupied: 0,
    rentPerBed: 22000,
    attachedBath: true,
    createdAt: '',
  },
  {
    id: 'r202',
    number: '202',
    floor: '1st',
    type: '4-sharing',
    capacity: 4,
    occupied: 3,
    rentPerBed: 9500,
    attachedBath: false,
    createdAt: '',
  },
  {
    id: 'r203',
    number: '203',
    floor: '1st',
    type: '2-sharing',
    capacity: 2,
    occupied: 2,
    rentPerBed: 14000,
    attachedBath: true,
    createdAt: '',
  },
  {
    id: 'r301',
    number: '301',
    floor: '2nd',
    type: '3-sharing',
    capacity: 3,
    occupied: 3,
    rentPerBed: 12000,
    attachedBath: false,
    createdAt: '',
  },
];

/** Stub tenants (Q-API pending). Matches design-mockups/13-tenants.html. */
export const TENANTS: Tenant[] = [
  {
    id: 't1',
    name: 'Ahmed Raza',
    phone: '0321 1234567',
    initials: 'AR',
    roomId: 'r102',
    roomNumber: '102',
    joined: '2026-01-12',
    rent: 12000,
    deposit: 12000,
    billingDate: 1,
    billingDueDate: 5,
    outstanding: 0,
    status: 'active',
  },
  {
    id: 't2',
    name: 'Bilal Khan',
    phone: '0300 9876543',
    initials: 'BK',
    roomId: 'r202',
    roomNumber: '202',
    joined: '2026-02-01',
    rent: 9500,
    deposit: 9500,
    billingDate: 1,
    billingDueDate: 7,
    outstanding: 9500,
    status: 'active',
  },
  {
    id: 't3',
    name: 'Saad Ali',
    phone: '0333 4567890',
    initials: 'SA',
    roomId: 'r101',
    roomNumber: '101',
    joined: '2025-12-20',
    rent: 14000,
    deposit: 14000,
    billingDate: 1,
    billingDueDate: 1,
    outstanding: 0,
    status: 'active',
  },
  {
    id: 't4',
    name: 'Usman Haider',
    phone: '0345 1122334',
    initials: 'UH',
    roomId: 'r301',
    roomNumber: '301',
    joined: '2025-11-10',
    checkedOut: '2026-05-31',
    rent: 12000,
    deposit: 12000,
    billingDate: 1,
    billingDueDate: 3,
    outstanding: 0,
    status: 'checked-out',
  },
  // Extra Room 101 occupants so the utilities pro-rata table matches the mockup (AR 30, BK 28, SA 30 over 88 days).
  {
    id: 't5',
    name: 'Ahmed Raza',
    phone: '0321 1234567',
    initials: 'AR',
    roomId: 'r101',
    roomNumber: '101',
    joined: '2026-06-01',
    rent: 14000,
    deposit: 14000,
    billingDate: 1,
    billingDueDate: 5,
    outstanding: 0,
    status: 'active',
  },
  {
    id: 't6',
    name: 'Bilal Khan',
    phone: '0300 9876543',
    initials: 'BK',
    roomId: 'r101',
    roomNumber: '101',
    joined: '2026-06-03',
    rent: 14000,
    deposit: 14000,
    billingDate: 1,
    billingDueDate: 7,
    outstanding: 0,
    status: 'active',
  },
];

/**
 * Occupancy-days per tenant for the current period, keyed by tenant id.
 * Day-weighted utility split divides the room bill across these. For Room 101
 * (June 2026): AR 30 + BK 28 + SA 30 = 88 occupancy-days — mirrors mockup 14.
 */
export const OCCUPANCY_DAYS: Record<string, number> = {
  t5: 30, // Ahmed Raza — full month
  t6: 28, // Bilal Khan — joined 3rd
  t3: 30, // Saad Ali — full month
};

/** Utility types + split method + metering — matched to /utility_bills/new API slugs. */
export const UTILITY_TYPES: UtilityTypeMeta[] = [
  {
    type: 'electricity',
    label: 'Electricity',
    icon: 'ti-bolt',
    metered: true,
    unit: 'kWh',
    split: 'prorata',
  },
  {
    type: 'gas',
    label: 'Gas',
    icon: 'ti-flame',
    metered: true,
    unit: 'units',
    split: 'prorata',
  },
  {
    type: 'water',
    label: 'Water',
    icon: 'ti-droplet',
    metered: true,
    unit: 'units',
    split: 'prorata',
  },
  {
    type: 'other',
    label: 'Other',
    icon: 'ti-receipt',
    metered: false,
    unit: '',
    split: 'prorata',
  },
];

export const UTILITY_META: Record<UtilityType, UtilityTypeMeta> =
  Object.fromEntries(UTILITY_TYPES.map((u) => [u.type, u])) as Record<
    UtilityType,
    UtilityTypeMeta
  >;

/** Stub batch line items (Q-API pending). Matches the bottom table of mockup 14. */
export const UTILITY_BATCH: UtilityBill[] = [
  {
    id: 'u1',
    roomId: 'r101',
    roomNumber: '101',
    tenantName: 'Ahmed Raza',
    type: 'electricity',
    startReading: 4210,
    endReading: 4307,
    units: 97,
    rate: 90,
    total: 8730,
    received: 8730,
    split: 'prorata',
  },
  {
    id: 'u2',
    roomId: 'r101',
    roomNumber: '101',
    tenantName: 'Bilal Khan',
    type: 'electricity',
    startReading: 1425,
    endReading: 1465,
    units: 40,
    rate: 90,
    total: 3600,
    received: 0,
    split: 'prorata',
  },
  {
    id: 'u3',
    roomId: 'r102',
    roomNumber: '102',
    tenantName: 'Saad Ali',
    type: 'electricity',
    startReading: 3037,
    endReading: 3210,
    units: 173,
    rate: 90,
    total: 15570,
    received: 5000,
    split: 'prorata',
  },
  {
    id: 'u4',
    roomId: 'r102',
    roomNumber: '102',
    tenantName: 'Usman Tariq',
    type: 'electricity',
    startReading: 1888,
    endReading: 2021,
    units: 133,
    rate: 90,
    total: 11970,
    received: 0,
    split: 'prorata',
  },
  {
    id: 'u5',
    roomId: 'r201',
    roomNumber: '201',
    tenantName: 'Kamran Shah',
    type: 'electricity',
    startReading: 2393,
    endReading: 2483,
    units: 90,
    rate: 90,
    total: 8100,
    received: 8100,
    split: 'prorata',
  },
  {
    id: 'u6',
    roomId: 'r202',
    roomNumber: '202',
    tenantName: 'Farhan Ahmed',
    type: 'other',
    startReading: null,
    endReading: null,
    units: null,
    rate: 0,
    total: 2000,
    received: 2000,
    split: 'equal',
  },
];

/** Stub invoices (Q-API pending). Matches design-mockups/15-invoices.html. */
export const INVOICES: Invoice[] = [
  {
    id: 'INV-2026-0142',
    tenantName: 'Ahmed Raza',
    roomNumber: '102',
    floor: '1st',
    kind: 'rent',
    amount: 20182,
    status: 'paid',
    issued: '2026-06-01',
    due: '2026-06-07',
    lines: [
      { label: 'Base rent — June', amount: 12000 },
      { label: 'Electricity share', amount: 8182 },
      { label: 'Previous balance', amount: 0 },
    ],
    payNote:
      'Payment: JazzCash 0321-1234567 (Imran Khan). Please share the receipt after payment. Thank you for staying with Al-Madina Boys Hostel.',
  },
  {
    id: 'INV-2026-0143',
    tenantName: 'Bilal Khan',
    roomNumber: '202',
    floor: '1st',
    kind: 'rent',
    amount: 9500,
    status: 'overdue',
    issued: '2026-06-01',
    due: '2026-06-07',
    lines: [
      { label: 'Base rent — June', amount: 9500 },
      { label: 'Previous balance', amount: 0 },
    ],
    payNote:
      'Payment: JazzCash 0321-1234567 (Imran Khan). Please share the receipt after payment. Thank you for staying with Al-Madina Boys Hostel.',
  },
  {
    id: 'INV-2026-0144',
    tenantName: 'Saad Ali',
    roomNumber: '101',
    floor: 'Ground',
    kind: 'utility',
    amount: 8000,
    status: 'unpaid',
    issued: '2026-06-01',
    due: '2026-06-07',
    lines: [{ label: 'Electricity share', amount: 8000 }],
    payNote:
      'Payment: JazzCash 0321-1234567 (Imran Khan). Please share the receipt after payment. Thank you for staying with Al-Madina Boys Hostel.',
  },
  {
    id: 'INV-2026-0145',
    tenantName: 'Usman Haider',
    roomNumber: '301',
    floor: '2nd',
    kind: 'rent',
    amount: 12000,
    status: 'paid',
    issued: '2026-06-01',
    due: '2026-06-07',
    lines: [
      { label: 'Base rent — June', amount: 12000 },
      { label: 'Previous balance', amount: 0 },
    ],
    payNote:
      'Payment: JazzCash 0321-1234567 (Imran Khan). Please share the receipt after payment. Thank you for staying with Al-Madina Boys Hostel.',
  },
];
