import {
  AuditEntry,
  DeltaGroup,
  DispositionMeta,
  ManagedListing,
  ModeratorProfile,
  QueueItem,
} from '@hostelhive/data-access';

/** Stub delta-media groups (Q-API pending). Matches design-mockups/22-delta-media.html. */
export const DELTA_GROUPS: DeltaGroup[] = [
  {
    id: 'al-madina',
    listingName: 'Al-Madina Boys Hostel',
    thumb: 'https://picsum.photos/seed/hhd1/60/60',
    host: 'Imran Khan',
    uploadedLabel: 'uploaded 3 photos · 1 hr ago',
    photos: [
      {
        id: 'dm1',
        url: 'https://picsum.photos/seed/hhdm1/240/180',
        tag: 'Rooftop',
      },
      {
        id: 'dm2',
        url: 'https://picsum.photos/seed/hhdm2/240/180',
        tag: 'Bedroom',
      },
      {
        id: 'dm3',
        url: 'https://picsum.photos/seed/hhdm3/240/180',
        tag: 'Kitchen',
      },
    ],
  },
  {
    id: 'gulberg',
    listingName: 'Gulberg Girls Residence',
    thumb: 'https://picsum.photos/seed/hhf2/60/60',
    host: 'Sana Malik',
    uploadedLabel: 'uploaded 2 photos · 4 hrs ago',
    photos: [
      {
        id: 'dm4',
        url: 'https://picsum.photos/seed/hhdm4/240/180',
        tag: 'Common',
      },
      {
        id: 'dm5',
        url: 'https://picsum.photos/seed/hhdm5/240/180',
        tag: 'Bathroom',
      },
    ],
  },
];

/** Disposition stat strip + filter chips (Q-API pending). Matches design-mockups/23-moderation-listings.html. */
export const DISPOSITIONS: DispositionMeta[] = [
  { value: 'all', label: 'All', count: 1482 },
  { value: 'published', label: 'Published', count: 1318 },
  { value: 'in-review', label: 'In review', count: 12 },
  { value: 'changes', label: 'Changes requested', count: 7 },
  { value: 'paused', label: 'Paused', count: 98 },
  { value: 'rejected', label: 'Rejected', count: 41 },
  { value: 'removed', label: 'Removed', count: 13 },
];

/** Stub managed listings (Q-API pending). Matches design-mockups/23-moderation-listings.html. */
export const MANAGED: ManagedListing[] = [
  {
    id: 'al-madina-boys-hostel',
    name: 'Al-Madina Boys Hostel',
    kind: 'boys',
    kindLabel: 'Boys',
    photoCount: 18,
    thumb: 'https://picsum.photos/seed/hhal1/80/80',
    city: 'Karachi',
    host: 'Imran Khan',
    disposition: 'published',
    updatedLabel: '2 hrs ago',
    views: 1204,
  },
  {
    id: 'city-nest-pg',
    name: 'City Nest PG',
    kind: 'coliving',
    kindLabel: 'Co-living',
    photoCount: 12,
    thumb: 'https://picsum.photos/seed/hhal2/80/80',
    city: 'Karachi',
    host: 'Imran Khan',
    disposition: 'in-review',
    updatedLabel: '2 days ago',
    views: null,
  },
  {
    id: 'iqra-girls-hostel',
    name: 'Iqra Girls Hostel',
    kind: 'girls',
    kindLabel: 'Girls',
    photoCount: 9,
    thumb: 'https://picsum.photos/seed/hhal3/80/80',
    city: 'Lahore',
    host: 'Sana Malik',
    disposition: 'changes',
    updatedLabel: '1 day ago',
    views: null,
  },
  {
    id: 'sunrise-lodge',
    name: 'Sunrise Lodge',
    kind: 'boys',
    kindLabel: 'Boys',
    photoCount: 11,
    thumb: 'https://picsum.photos/seed/hhal4/80/80',
    city: 'Islamabad',
    host: 'Hassan Ali',
    disposition: 'paused',
    updatedLabel: '3 wks ago',
    views: 872,
  },
  {
    id: 'metro-inn-pg',
    name: 'Metro Inn PG',
    kind: 'coliving',
    kindLabel: 'Co-living',
    photoCount: 6,
    thumb: 'https://picsum.photos/seed/hhal5/80/80',
    city: 'Rawalpindi',
    host: 'Adeel Riaz',
    disposition: 'rejected',
    updatedLabel: '1 mo ago',
    views: null,
  },
  {
    id: 'star-boys-hostel',
    name: 'Star Boys Hostel',
    kind: 'boys',
    kindLabel: 'Boys',
    photoCount: 0,
    thumb: 'https://picsum.photos/seed/hhal6/80/80',
    city: 'Lahore',
    host: 'M. Faisal',
    disposition: 'removed',
    updatedLabel: '2 mo ago',
    views: null,
    removedNote: 'Removed by admin · policy violation',
  },
];

/** Stub audit timeline (Q-API pending). Matches design-mockups/24-moderation-audit.html. */
export const AUDIT: AuditEntry[] = [
  {
    id: 'au1',
    kind: 'approve',
    group: 'approvals',
    icon: 'ti-rosette-discount-check',
    iconTone: 'ok',
    actor: 'Maria Shah',
    action: 'approved & published',
    target: 'Capital Boys Lodge',
    targetLink: '/moderator/review/capital-boys-lodge',
    tail: '',
    detail: 'Host notified by email · listing now public',
    day: 'Today · 11 June 2026',
    time: '14:32',
  },
  {
    id: 'au2',
    kind: 'reject-photo',
    group: 'rejections',
    icon: 'ti-photo-x',
    iconTone: 'danger',
    actor: 'Maria Shah',
    action: 'rejected 1 photo on',
    target: 'City Nest PG',
    targetLink: '/moderator/review/city-nest-pg',
    tail: '',
    detail: 'Reason: blurry · photo #3 (bedroom)',
    day: 'Today · 11 June 2026',
    time: '14:18',
  },
  {
    id: 'au3',
    kind: 'edit',
    group: 'edits',
    icon: 'ti-edit',
    iconTone: 'neutral',
    actor: 'Maria Shah',
    action: 'edited the description of',
    target: 'City Nest PG',
    targetLink: '/moderator/review/city-nest-pg',
    tail: '',
    detail: '',
    diff: {
      before: '"best hostel in twon"',
      after: '"Modern co-living space in Gulshan…"',
    },
    day: 'Today · 11 June 2026',
    time: '14:11',
  },
  {
    id: 'au4',
    kind: 'approve-media',
    group: 'media',
    icon: 'ti-photo-check',
    iconTone: 'ok',
    actor: 'Ali Hamza',
    action: 'approved 3 pending photos on live listing',
    target: 'Al-Madina Boys Hostel',
    targetLink: '/moderator/media',
    tail: '',
    detail: 'Delta media pipeline · photos now public',
    day: 'Today · 11 June 2026',
    time: '11:47',
  },
  {
    id: 'au5',
    kind: 'flag',
    group: 'edits',
    icon: 'ti-flag',
    iconTone: 'warn',
    actor: 'Ali Hamza',
    action: 'flagged the map pin on',
    target: 'Garden View Hostel',
    targetLink: '/moderator/review/garden-view-hostel',
    tail: 'for host correction',
    detail: 'Pin ~400m from stated street address',
    day: 'Today · 11 June 2026',
    time: '10:05',
  },
  {
    id: 'au6',
    kind: 'request-changes',
    group: 'edits',
    icon: 'ti-pencil',
    iconTone: 'warn',
    actor: 'Maria Shah',
    action: 'requested changes on',
    target: 'Iqra Girls Hostel',
    targetLink: '/moderator/review/iqra-girls-hostel',
    tail: '',
    detail: 'Notes: add facade photo, confirm 1-sharing price · host emailed',
    day: 'Yesterday · 10 June 2026',
    time: '16:40',
  },
  {
    id: 'au7',
    kind: 'reject',
    group: 'rejections',
    icon: 'ti-x',
    iconTone: 'danger',
    actor: 'Maria Shah',
    action: 'rejected',
    target: 'Metro Inn PG',
    targetLink: '/admin/listings',
    tail: '',
    detail: 'Reason: duplicate of existing listing · refund policy link sent',
    day: 'Yesterday · 10 June 2026',
    time: '12:22',
  },
  {
    id: 'au8',
    kind: 'set-primary',
    group: 'edits',
    icon: 'ti-star',
    iconTone: 'neutral',
    actor: 'Ali Hamza',
    action: 'set a new primary image on',
    target: 'Sunrise Lodge',
    targetLink: '/moderator/review/sunrise-lodge',
    tail: '',
    detail: 'facade.jpg → search thumbnail updated',
    day: 'Yesterday · 10 June 2026',
    time: '09:51',
  },
  {
    id: 'au9',
    kind: 'remove',
    group: 'rejections',
    icon: 'ti-trash',
    iconTone: 'danger',
    actor: 'Admin (S. Qureshi)',
    action: 'removed',
    target: 'Star Boys Hostel',
    targetLink: '',
    tail: '',
    detail: 'Policy violation · fake photos reported · host suspended',
    day: 'Yesterday · 10 June 2026',
    time: '08:15',
  },
];

/** Signed-in moderator profile (Q-API pending). Matches design-mockups/25-moderation-settings.html. */
export const PROFILE: ModeratorProfile = {
  name: 'Maria Shah',
  initials: 'MS',
  email: 'maria.shah@hostelhive.com',
  role: 'Moderator',
  passwordChangedLabel: 'Last changed 12 days ago',
  sessionLengthLabel: 'Moderator sessions expire after 8 hours',
  prefs: {
    defaultSort: 'Days in queue · longest first',
    perPage: '20 (platform default)',
    badgeNewMedia: true,
    emailNewSubmissions: true,
    ageingAlert: false,
  },
  ipAllowlist: [
    { cidr: '182.176.x.x', label: 'Office' },
    { cidr: '39.50.x.x', label: 'VPN' },
  ],
  sessions: [
    { id: 's1', device: 'Chrome · Windows · Office network', current: true },
  ],
};
