import { Injectable, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { Capacitor } from '@capacitor/core';

/**
 * Header names carrying the push identity to the API. `X-FCM-Token` is the name the
 * backend reads; `X-Device-Id` carries the registration id the token is stored
 * against — regenerated on every sign-out, so each session gets its own key.
 */
export const FCM_TOKEN_HEADER = 'X-FCM-Token';
export const REGISTRATION_ID_HEADER = 'X-Device-Id';

type PermissionState = 'granted' | 'denied' | 'prompt' | 'unsupported';

/**
 * Owns the device's FCM registration.
 *
 * The token is issued by Firebase — not derived from a device id, a timestamp, or
 * anything else we control — and it arrives asynchronously via the `registration`
 * listener, so it is exposed as a signal that starts null and fills in once Firebase
 * answers.
 *
 * On sign-out `rotate()` deletes it at Firebase and obtains a new one, so a token is
 * never reused across two sessions and the previous user cannot be reached on this
 * device once they log out.
 *
 * No-ops off-native, and the plugins are imported dynamically so they stay out of the
 * web bundle's eager path (same reasoning as `capacitor/native.ts`).
 */
@Injectable({ providedIn: 'root' })
export class PushNotificationsService {
  /** FCM registration token, or null until Firebase issues one (or if unavailable). */
  readonly token = signal<string | null>(null);
  /**
   * The id this registration is stored against. Generated by us, and regenerated on
   * every `rotate()`, so each session gets its own key.
   *
   * Deliberately not `Device.getId()`: that value is fixed for the life of the install
   * and identifies the device forever, so it cannot key a per-session registration.
   */
  readonly registrationId = signal<string | null>(null);
  readonly permission = signal<PermissionState>('unsupported');
  /** Last error reported by the platform's registration attempt, for diagnostics. */
  readonly registrationError = signal<string | null>(null);
  /**
   * Increments whenever a push lands while the app is in the foreground. Anything
   * showing unread state (the notification bell) can react to it — Android raises no
   * tray notification in that case, so without a cue the user sees nothing at all.
   */
  readonly received = signal(0);

  private readonly router = inject(Router);

  private registered = false;
  private listenersBound = false;

  /**
   * Registers with FCM, optionally asking for notification permission first.
   *
   * `prompt` decides whether the Android 13+ POST_NOTIFICATIONS dialog may be shown:
   *
   *   - `init()` — silent. Registers only if permission was already granted. Used on
   *     app start so a returning user with a restored session still has a token,
   *     without a dialog ambushing them before they have seen anything.
   *   - `init({ prompt: true })` — may show the dialog. Used once a sign-in succeeds,
   *     which is when notifications first mean something to the user.
   *
   * The timing matters more than it looks: on Android 13+ the system stops showing the
   * dialog once it has been dismissed, so a denial earned at cold start is close to
   * unrecoverable — the user has to be walked into system Settings to undo it.
   *
   * Re-entrant until registration actually succeeds, so a silent attempt that bails on
   * a missing permission does not block the prompting attempt that follows login.
   */
  async init(options: { prompt?: boolean } = {}): Promise<void> {
    if (this.registered || !Capacitor.isNativePlatform()) return;

    const { PushNotifications: Push } = await import(
      '@capacitor/push-notifications'
    );

    // Bind before register(), or a fast callback is missed. Guarded so repeated
    // init() attempts do not stack duplicate listeners.
    if (!this.listenersBound) {
      this.listenersBound = true;
      await Push.addListener('registration', (t) => {
        this.registrationError.set(null);
        this.token.set(t.value);
      });
      await Push.addListener('registrationError', (err) => {
        this.registrationError.set(String(err?.error ?? 'registration failed'));
        this.token.set(null);
      });

      // Tapping a notification in the system tray opens the app here.
      await Push.addListener('pushNotificationActionPerformed', () => {
        this.openNotifications();
      });

      // Arrives while the app is already open. Android does not raise a tray
      // notification in that case, so the only cue the user gets is the bell — bump
      // its unread count rather than navigating, which would yank them off whatever
      // they were doing.
      await Push.addListener('pushNotificationReceived', () => {
        this.received.update((n) => n + 1);
      });
    }

    try {
      let status = await Push.checkPermissions();
      if (status.receive !== 'granted') {
        // Not granted yet — only the prompting caller may raise the dialog.
        if (!options.prompt) return;
        status = await Push.requestPermissions();
      }
      this.permission.set(status.receive === 'granted' ? 'granted' : 'denied');
      if (status.receive !== 'granted') return;

      if (!this.registrationId()) this.registrationId.set(crypto.randomUUID());
      await Push.register();
      this.registered = true;
    } catch (e) {
      this.registrationError.set(String(e));
      this.permission.set('denied');
    }
  }

  /**
   * Send the user to the notifications list after they tap a notification.
   *
   * `/notifications` is auth-guarded, so a tap while signed out would bounce to the
   * auth wall — `returnUrl` brings them back afterwards instead of stranding them on
   * the landing page.
   *
   * A tap can also cold-start the app, in which case this may run before the router
   * has finished its first navigation and the call would be swallowed. Deferring to a
   * microtask lets bootstrap settle first; `navigateByUrl` is idempotent here, so the
   * worst case is landing on the page the user was already heading to.
   *
   * Per-notification routing (invoice vs. invite vs. mess) needs a `data` block on the
   * payload that the backend does not send yet. Until then every tap lands on the
   * list, which is at least always correct.
   */
  private openNotifications(): void {
    queueMicrotask(() => {
      void this.router.navigateByUrl('/notifications').catch(() => {
        void this.router.navigateByUrl('/auth?returnUrl=/notifications');
      });
    });
  }

  /**
   * Discards the current registration and obtains a brand-new one: a fresh FCM token
   * and a fresh registration id.
   *
   * Called on sign-out rather than on sign-in, deliberately. The headers have to be
   * present *on* the sign-in request, and Firebase issues a token asynchronously — so
   * rotating at sign-in would mean either blocking the login call until Firebase
   * answers, or sending the old token anyway. Rotating at sign-out means the next
   * sign-in already has fresh values ready to send.
   *
   * `unregister()` deletes the token at Firebase, so the old value is genuinely dead
   * and cannot be used to reach this device again — the previous user stops receiving
   * anything the moment they log out.
   *
   * The registration id is ours, generated per rotation. `Device.getId()` is fixed for
   * the life of the install and could not serve as a per-session key.
   */
  async rotate(): Promise<void> {
    this.token.set(null);
    this.registrationId.set(null);
    this.registered = false;
    if (!Capacitor.isNativePlatform()) return;

    const { PushNotifications: Push } = await import(
      '@capacitor/push-notifications'
    );
    try {
      await Push.unregister();
      // Permission survives sign-out, so this re-registers without a dialog.
      await this.init();
    } catch (e) {
      this.registrationError.set(String(e));
    }
  }
}
